print("Welcome to cricket clans")
print("A fun cricket game to make the ultimate team with highest OVR possible")
print("Let me guide you to get the basic controls of the game")
print("click kick off to start your journey")
user= input ("clicks to start")
if user == "clicks":
 print("OK So do you want to skip the tutorial or not?")
user1= input ("type skip to skip the tutorial or type continue to continue with the tutorial")

if user1 == "skip":
        print("OK you have skipped the tutorial")

elif user1 == "continue": 
 print("Great you have chosen to continue with the tutorial")
 print("In this game you have to make your team and play matches to increase your OVR")
 print("You can buy players from the market and sell them to make profit")
 print("You can also train your players to increase their OVR")
 print("You can also participate in tournaments to win prizes")
 print("So what are you waiting for? Start building your team and become the ultimate cricket clan!")

else: print("Invalid input, please type skip or continue")

print("this is just a basic interface for the game, you can add more features and options as you like to make it more interactive and fun")